### ISSUE TITLE
Install problem under Python

### ISSUE THREAD

**Issue by gapore** [mirca/lad#3]
When I type 'pip install lad' in cmd window, I just get the following error message :

Collecting lad
  Using cached https://files.pythonhosted.org/packages/32/56/848319f8dba746a90dd5f6816841e92262387a0f2aa84775f1055f3033d1/lad-0.1.dev3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Home\AppData\Local\Temp\pip-install-4t08t_o4\lad\setup.py", line 19, in <module>
        with open(path.join(here, '../README.rst'), encoding='utf-8') as f:
      File "c:\users\home\appdata\local\programs\python\python36\lib\codecs.py", line 897, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Home\\AppData\\Local\\Temp\\pip-install-4t08t_o4\\lad\\../README.rst'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in
C:\Users\Home\AppData\Local\Temp\pip-install-4t08t_o4\lad\

Can you help me about this?

**Comment by mirca** [comment]
Hi @gapore, I pushed a fix to PYPI, can you try installing it again with ``pip install --upgrade lad``?

Thank you very much for raising this issue, it actually made me add an appveyor build to the project so that the project's sanity can be checked on a Windows environment!

Let me know if the problem has been solved on your end!

**Comment by gapore** [comment]
Thank you! Now it works well.

**Comment by mirca** [comment]
@gapore awesome!
